version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build:
      context: .
    depends_on:
      - qdrant
    working_dir: /app
    environment:
      QDRANT_HOST: qdrant
    ports:
      - "7860:7860"
    command: python main.py

volumes:
  qdrant_data:
